if: tag IS blank

language: node_js
node_js:
  - '10.13'
  
matrix:
  include:
    - name: "Linux Build"
      os: linux
    
    - name: "Mac Build"
      os: osx
      
    - name: "Windows Build"
      os: windows
    
before_install:
  - if [ [$TRAVIS_OS_NAME == 'linux'] OR [$TRAVIS_OS_NAME == 'osx'] ]; then travis_retry npm i -g npm@6.4.0; fi
  - bash travis_scripts/get_os.sh
  - echo "$OS_FLAG"
install:
  - travis_retry npm install
  - npm update
script:
  - ls ./node_modules/@angular/cli/bin/
  - |
    if [[ $TRAVIS_BRANCH == 'master' ]]; then
      travis_wait 30 npm run ng-high-memory
      ./node_modules/.bin/build -"$OS_FLAG" --x64 --publish="never"
      ls
      ls ../output/
    else
      npm run build
    fi
  
before_deploy:
  #function keep_alive() {
  #  while true; do
  #    echo -en "\a"
  #    sleep 5
  #  done
  #}
  #keep_alive &
  - export TRAVIS_TAG="release_draft"
deploy:
  provider: releases
  api_key:
    secure: iRdxjibRf0cHrjX26NqqeH6jvqrnNbOYaxRe/zbQWXs3Lx1jZg8Rh7a3i5SCXY3UGKm0uVfeASPM7HAaRgwZaml2tXsJW4Gkz0YxOvfAWB+LRNredQSHHUHpfIxZU24oMDYgm2yWpsa2jEbJsdMtv3yoRyv2BHDCyCjmfwfFJpxqfrG1kJdjiGqahsuamv7mf3nPmnRCdVLPlwCPhp/BlcqYGNpkhXi0q4/RYU2BB4W+8ZOHfjkXN7ff8KHjz/Jux5U4LRHN0PBxfqnrLByZHFCXp7fT1SM8QUFTovHX7BsSdUWL2ufs+CMeG4H6pPk///VKx0AqVmY4T7pk0xnqbvTZvPQck0jXitDSjRQCo2J8v6tBzQfrWW5nnpqSGKsJyxXQMkjRMMn7VQ68H6VCJjgjKRV1duN7RMw2h8K04FZR0a0emyVyQZFw6HcnSlHQPSuy5/c04jpLZymKWlYVJXkXzrKO6W2ry0TTdRDJmQzxbeeYbmSKlnlZZWXnmeozVDy8mHv99134P93KzGDoet8CCo+WSiz7aYbcIvPwA72bSCnM+XOylHOD45kEV0a99xaLhHV6GjexY4yVPn0z4mRk5/f4WorR2te3rYJRobb29qRBR1TlMZb8LvHPz5cRSzHP2k5WdviEmuvTYhwx60CsOlxKKBo0cXi93ig3MJg=
  file:
    - "../output/MEASUR-0.6.5-beta.AppImage"
    - "../output/MEASUR-0.6.5-beta.tar.gz"
    - "../output/latest-linux.yml"
    - "../output/MEASUR-0.6.5-beta.dmg"
    - "../output/latest-mac.yml"
    - "../output/MEASUR-Setup-0.6.5-beta.exe"
    - "../output/latest.yml"
  overwrite: true
  skip_cleanup: true
  draft: true
  name: "RELEASE DRAFT"
  #tag_name: "release_draft"
  on:
    repo: ORNL-AMO/AMO-Tools-Desktop
    branch: master
    #condition: type = push AND branch = master
    #tags: false

